/* Ø¹Ø§Ø¦Ù„Ø© Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ© â€” static, privacy-preserving reference implementation */
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const STORAGE = 'anasweh-tree-v1';
const makeId = () => crypto.randomUUID ? crypto.randomUUID() : `uuid-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const initialPeople = [
  ['2d1cf840-8174-4418-ae84-010000000001','Ø§Ù„Ø´ÙŠØ® Ù…Ø­Ù…Ø¯ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A',1882,'','', 'Ù…Ù† Ø£ÙˆØ§Ø¦Ù„ Ù…Ù† Ø­ÙØ¸Øª Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø­ÙƒØ§ÙŠØ§ØªÙ‡Ù… ÙÙŠ Ø§Ù„Ø³Ù„Ø·.'],
  ['2d1cf840-8174-4418-ae84-010000000002','Ø³Ù„ÙŠÙ…Ø§Ù† Ù…Ø­Ù…Ø¯ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1',1910,'2d1cf840-8174-4418-ae84-010000000001','2d1cf840-8174-4418-ae84-010000000009',''],
  ['2d1cf840-8174-4418-ae84-010000000003','Ø¹Ù„ÙŠ Ù…Ø­Ù…Ø¯ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-2',1916,'2d1cf840-8174-4418-ae84-010000000001','',''],
  ['2d1cf840-8174-4418-ae84-010000000004','ÙŠÙˆØ³Ù Ù…Ø­Ù…Ø¯ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-3',1921,'2d1cf840-8174-4418-ae84-010000000001','',''],
  ['2d1cf840-8174-4418-ae84-010000000005','Ø£Ø­Ù…Ø¯ Ø³Ù„ÙŠÙ…Ø§Ù† Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1-1',1942,'2d1cf840-8174-4418-ae84-010000000002','',''],
  ['2d1cf840-8174-4418-ae84-010000000006','Ø®Ø§Ù„Ø¯ Ø³Ù„ÙŠÙ…Ø§Ù† Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1-2',1948,'2d1cf840-8174-4418-ae84-010000000002','',''],
  ['2d1cf840-8174-4418-ae84-010000000007','Ù…Ù†Ù‰ Ø³Ù„ÙŠÙ…Ø§Ù† Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1-3',1954,'2d1cf840-8174-4418-ae84-010000000002','',''],
  ['2d1cf840-8174-4418-ae84-010000000008','Ø£Ù†Ø³ Ø£Ø­Ù…Ø¯ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1-1-1',1974,'2d1cf840-8174-4418-ae84-010000000005','','Ù…Ù‡Ù†Ø¯Ø³ ÙˆØ±Ø§ÙˆÙ Ù„Ø­ÙƒØ§ÙŠØ§Øª Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©.'],
  ['2d1cf840-8174-4418-ae84-010000000009','Ø®Ø¯ÙŠØ¬Ø© Ø¹Ø¨Ø¯ Ø§Ù„Ù„Ù‡','S-1',1917,'','','Ø²ÙˆØ¬Ø© Ø³Ù„ÙŠÙ…Ø§Ù†Ø› ÙŠØ¸Ù‡Ø± Ø±Ù…Ø² Ù…Ù†ÙØµÙ„ Ù„Ù„ÙØ±ÙˆØ¹ Ø§Ù„ÙˆØ§Ø±Ø¯Ø©.'],
  ['2d1cf840-8174-4418-ae84-010000000010','Ù„ÙŠØ§Ù† Ø£Ù†Ø³ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1-1-1-1',2001,'2d1cf840-8174-4418-ae84-010000000008','',''],
  ['2d1cf840-8174-4418-ae84-010000000011','Ø£Ø­Ù…Ø¯ Ø£Ù†Ø³ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©','A-1-1-1-2',2005,'2d1cf840-8174-4418-ae84-010000000008','','']
].map(([id,name,lineageCode,birthYear,parentId,spouseId,note])=>({id,name,lineageCode,birthYear,parentId,spouseId,note,living:birthYear>1940}));
let state = {people: initialPeople, audit: [], expanded: new Set(), selected: null, layout:'vertical', transform:{x:0,y:0,scale:1}, undo:[]};
try { const saved=JSON.parse(localStorage.getItem(STORAGE)); if(saved?.people?.length) state={...state,...saved,expanded:new Set(saved.expanded||[])}; } catch(e) {}
const save = () => localStorage.setItem(STORAGE, JSON.stringify({...state,expanded:[...state.expanded],undo:[]}));
const person = id => state.people.find(p=>p.id===id);
const children = id => state.people.filter(p=>p.parentId===id);
const roots = () => state.people.filter(p=>!p.parentId || !person(p.parentId));
const displayId = p => p?.lineageCode || 'â€”';
function normalizeArabic(value='') { return value.toLowerCase().normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[Ø£Ø¥Ø¢Ù±]/g,'Ø§').replace(/Ù‰/g,'ÙŠ').replace(/Ø©/g,'Ù‡').replace(/Ø¤/g,'Ùˆ').replace(/Ø¦/g,'ÙŠ').replace(/[Ù€\s\-]/g,''); }
function score(query, p) { const q=normalizeArabic(query), name=normalizeArabic(p.name), code=(p.lineageCode||'').toLowerCase(); if(code.includes(query.toLowerCase())) return 100; const parts=q.split(/\s+/).filter(Boolean); if(parts.every(x=>name.includes(x))) return 80+parts.length; let i=0; for(const c of q) { i=name.indexOf(c,i); if(i<0) return 0; i++; } return q.length>2?30:0; }
function toast(text) { const t=$('#toast'); t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2700); }
function audit(action, detail) { state.audit.unshift({id:makeId(),action,detail,at:new Date().toLocaleString('ar-JO')}); state.audit=state.audit.slice(0,80); }
function snapshot(label) { state.undo.push({label,people:structuredClone(state.people)}); state.undo=state.undo.slice(-12); }
function undo() { const previous=state.undo.pop(); if(!previous) return toast('Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù…Ù„ÙŠØ© Ù‚Ø§Ø¨Ù„Ø© Ù„Ù„ØªØ±Ø§Ø¬Ø¹'); state.people=previous.people;audit('ØªØ±Ø§Ø¬Ø¹',previous.label);save();renderAll();toast('ØªÙ… Ø§Ù„ØªØ±Ø§Ø¬Ø¹ Ø¹Ù†: '+previous.label); }
function openModal(id) { $('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false'); }
function closeModal(id) { $('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true'); }
function initials(name){return (name||'?').trim().charAt(0)}
function renderSearch(query='') { const box=$('#searchResults'); if(!query.trim()) {box.innerHTML='';return;} const found=state.people.map(p=>({p,s:score(query,p)})).filter(x=>x.s).sort((a,b)=>b.s-a.s).slice(0,8); box.innerHTML=found.length ? found.map(({p})=>`<button class="search-result" data-focus="${p.id}"><b>${p.name}</b><small>${displayId(p)}</small></button>`).join('') : '<div class="search-result">Ù„Ø§ ØªÙˆØ¬Ø¯ Ù†ØªØ§Ø¦Ø¬ Ù…Ø·Ø§Ø¨Ù‚Ø©. Ø¬Ø±Ù‘Ø¨ ÙƒØªØ§Ø¨Ø© Ø¬Ø²Ø¡ Ù…Ù† Ø§Ù„Ø§Ø³Ù….</div>';
}
function visibleTree() {
  const out=[], walk=(p,depth)=>{out.push({p,depth}); if(state.expanded.has(p.id)) children(p.id).forEach(c=>walk(c,depth+1));};
  roots().forEach(r=>walk(r,0)); return out;
}
function calculatePositions(items) {
  const map=new Map(items.map(x=>[x.p.id,{...x,x:0,y:0}])); let leaves=0;
  const place=(id,depth)=>{ const current=map.get(id), kids=children(id).filter(k=>map.has(k.id)); if(!kids.length) current.x=leaves++*210; else {kids.forEach(k=>place(k.id,depth+1));current.x=(map.get(kids[0].id).x+map.get(kids.at(-1).id).x)/2;} current.y=depth*145; };
  roots().filter(r=>map.has(r.id)).forEach((r,i)=>{if(i&&leaves) leaves++;place(r.id,0)});
  if(state.layout==='horizontal') map.forEach(point=>{const generation=point.y, branch=point.x; point.x=generation*235; point.y=branch*.68;});
  return map;
}
function addLink(world,a,b){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),line=document.createElement('i');line.className='tree-link';line.style.width=`${len}px`;line.style.left=`${a.x}px`;line.style.top=`${a.y}px`;line.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;world.append(line)}
function renderTree() {
  const world=$('#treeWorld'),items=visibleTree(), coords=calculatePositions(items);world.innerHTML='';$('#treeEmpty').hidden=!!items.length;
  // Links first, then nodes. Rendering is bounded by open branchesâ€”not the full directory.
  items.forEach(({p})=>{if(p.parentId&&coords.has(p.parentId)) addLink(world,coords.get(p.parentId),coords.get(p.id));});
  items.forEach(({p,depth})=>{const c=coords.get(p.id), kids=children(p.id), node=document.createElement('button');node.className=`tree-node ${!kids.length?'leaf':''} ${!p.parentId?'root':''} ${state.selected===p.id?'selected':''}`;node.style.left=`${c.x}px`;node.style.top=`${c.y}px`;node.dataset.id=p.id;node.innerHTML=`<span class="avatar">${initials(p.name)}</span><span class="node-name">${p.name}</span><span class="node-meta">${displayId(p)} Â· ${p.birthYear||'â€”'}</span>${kids.length?`<span class="branch-toggle" data-toggle="${p.id}" aria-label="${state.expanded.has(p.id)?'Ø·ÙŠ':'ØªÙˆØ³ÙŠØ¹'} ÙØ±Ø¹ ${p.name}">${state.expanded.has(p.id)?'âˆ’':'+'}</span>`:''}`;world.append(node);});
  applyTransform(); $('#treeStatus').textContent=`${items.length.toLocaleString('ar-JO')} Ø´Ø®Øµ Ø¸Ø§Ù‡Ø± Â· Ø§Ø³Ø­Ø¨ Ù„Ù„ØªÙ†Ù‚Ù„ Â· ÙƒØ¨Ù‘Ø± Ø¨Ø¥ØµØ¨Ø¹ÙŠÙ†`;
}
function applyTransform(){const t=state.transform;$('#treeWorld').style.transform=`translate(${t.x}px,${t.y}px) scale(${t.scale})`;}
function centerTree(targetId=roots()[0]?.id) {const canvas=$('#treeCanvas'),p=targetId&&person(targetId); if(!p)return;const items=visibleTree(),c=calculatePositions(items).get(p.id);if(!c)return;state.transform={x:canvas.clientWidth/2-c.x*state.transform.scale,y:Math.max(100,canvas.clientHeight*.25-c.y*state.transform.scale),scale:state.transform.scale};applyTransform();}
function focusPerson(id) { const chain=[];let p=person(id);while(p?.parentId){chain.push(p.parentId);p=person(p.parentId)}chain.forEach(x=>state.expanded.add(x));state.selected=id;renderTree();requestAnimationFrame(()=>centerTree(id));renderPerson(id); }
function renderPerson(id) {const p=person(id);if(!p)return; const parent=person(p.parentId), spouse=person(p.spouseId), kids=children(id);$('#personContent').innerHTML=`<div class="person-hero"><div class="person-initial">${initials(p.name)}</div><h2>${p.name}</h2><small>${displayId(p)} Â· ${p.id}</small></div><div class="detail-grid"><div><span>Ø³Ù†Ø© Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯</span><b>${p.birthYear||'ØºÙŠØ± Ù…Ø³Ø¬Ù„'}</b></div><div><span>Ø§Ù„Ø­Ø§Ù„Ø©</span><b>${p.living?'Ø¹Ù„Ù‰ Ù‚ÙŠØ¯ Ø§Ù„Ø­ÙŠØ§Ø©':'Ù…ØªÙˆÙÙ‰'}</b></div><div><span>Ø§Ù„Ø£ØµÙ„ / Ø§Ù„ÙˆØ§Ù„Ø¯</span><b>${parent?.name||'ØºÙŠØ± Ù…Ø±Ø¨ÙˆØ·'}</b></div><div><span>Ø§Ù„Ø£Ø¨Ù†Ø§Ø¡ Ø§Ù„Ø¸Ø§Ù‡Ø±ÙˆÙ†</span><b>${kids.length}</b></div>${spouse?`<div><span>Ø§Ù„Ø²ÙˆØ¬ / Ø§Ù„Ø²ÙˆØ¬Ø©</span><b>${spouse.name}</b></div>`:''}</div>${p.note?`<p class="person-note">${p.note}</p>`:''}<div class="person-actions"><button data-panel-focus="${p.parentId||''}" ${!p.parentId?'disabled':''}>â†‘ Ø§Ù„Ø§Ù†ØªÙ‚Ø§Ù„ Ø¥Ù„Ù‰ Ø§Ù„ÙˆØ§Ù„Ø¯</button><button class="primary" data-request-person="${p.name} Â· ${displayId(p)}">Ø§Ù‚ØªØ±Ø­ ØªØ¹Ø¯ÙŠÙ„Ù‹Ø§ Ù„Ù‡Ø°Ù‡ Ø§Ù„Ø¨Ø·Ø§Ù‚Ø©</button></div>`;$('#personPanel').classList.add('open');$('#personPanel').setAttribute('aria-hidden','false');}
function renderAdmin(){const list=$('#adminPeople');list.innerHTML=state.people.slice().sort((a,b)=>a.name.localeCompare(b.name,'ar')).map(p=>`<div class="person-row"><span><b>${p.name}</b><small>${displayId(p)} Â· ${p.id.slice(0,8)}</small></span><button data-edit="${p.id}">ØªØ­Ø±ÙŠØ±</button></div>`).join('');$('#auditList').innerHTML=state.audit.length?state.audit.map(a=>`<div class="audit-item"><b>${a.action}</b> â€” ${a.detail}<small>${a.at}</small></div>`).join(''):'<p>Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù…Ù„ÙŠØ§Øª Ù…Ø³Ø¬Ù„Ø© Ø¨Ø¹Ø¯.</p>';}
function renderAll(){renderTree();renderAdmin();}
function populateSelects(currentId=''){const options=state.people.filter(p=>p.id!==currentId).sort((a,b)=>a.name.localeCompare(b.name,'ar')).map(p=>`<option value="${p.id}">${p.name} (${displayId(p)})</option>`).join('');$('[name=parentId]').innerHTML='<option value="">Ø¨Ø¯ÙˆÙ† Ø±Ø¨Ø· Ø­Ø§Ù„ÙŠÙ‹Ø§</option>'+options;$('[name=spouseId]').innerHTML='<option value="">Ø¨Ø¯ÙˆÙ† Ø±Ø¨Ø· Ø­Ø§Ù„ÙŠÙ‹Ø§</option>'+options;}
function openEditor(id=''){const form=$('#personForm'),p=person(id);form.reset();populateSelects(id);$('#deletePersonBtn').hidden=!p;$('#formMode').textContent=p?'ØªØ¹Ø¯ÙŠÙ„ Ù…Ø¹ Ù…Ø¹Ø§ÙŠÙ†Ø©':'Ø¥Ø¶Ø§ÙØ©';$('#formTitle').textContent=p?p.name:'Ø´Ø®Øµ Ø¬Ø¯ÙŠØ¯';if(p) Object.entries(p).forEach(([k,v])=>{const f=form.elements[k];if(f)f.value=String(v??'')});form.elements.living.value=p?.living===false?'false':'true';previewRelationship();openModal('editorModal');}
function isDescendant(candidateId, ancestorId){let p=person(candidateId);while(p?.parentId){if(p.parentId===ancestorId)return true;p=person(p.parentId)}return false}
function previewRelationship(){const f=$('#personForm').elements,parent=person(f.parentId.value),spouse=person(f.spouseId.value), self=f.id.value;let errors=[];if(self&&f.parentId.value===self)errors.push('Ù„Ø§ ÙŠÙ…ÙƒÙ† Ø£Ù† ÙŠÙƒÙˆÙ† Ø§Ù„Ø´Ø®Øµ ÙˆØ§Ù„Ø¯Ù‡/ÙˆØ§Ù„Ø¯ØªÙ‡.');if(self&&isDescendant(f.parentId.value,self))errors.push('Ù‡Ø°Ø§ Ø§Ù„Ø±Ø¨Ø· Ø³ÙŠØµÙ†Ø¹ Ø­Ù„Ù‚Ø© ÙÙŠ Ø§Ù„Ø´Ø¬Ø±Ø©.');$('#relationshipPreview').textContent=errors.length?errors.join(' '):`Ù…Ø¹Ø§ÙŠÙ†Ø©: ${parent?`Ø³ÙŠØ±ØªØ¨Ø· Ø¨Ù€ ${parent.name} ÙƒÙˆØ§Ù„Ø¯/Ø©.`:'Ù„Ù† ÙŠØ±Ø¨Ø· Ø¨ÙˆØ§Ù„Ø¯ Ø§Ù„Ø¢Ù†.'} ${spouse?`ÙˆØ§Ù„Ø²ÙˆØ¬/Ø©: ${spouse.name}.`:''}`;return !errors.length;}
function seedLarge(){if(!confirm('Ø³ÙŠØ³ØªØ¨Ø¯Ù„ Ù‡Ø°Ø§ Ø§Ù„Ø¹Ø±Ø¶ Ø§Ù„Ù…Ø­Ù„ÙŠ Ø¨Ø¹ÙŠÙ†Ø© Ø§Ø®ØªØ¨Ø§Ø± Ù…Ù† 1,200 Ø´Ø®Øµ. ÙŠÙ…ÙƒÙ† Ø§Ù„ØªØ±Ø§Ø¬Ø¹ Ù…Ø±Ø© ÙˆØ§Ø­Ø¯Ø©.'))return;snapshot('Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„ÙƒØ¨ÙŠØ±Ø©');const root={id:makeId(),name:'Ø§Ù„Ø¬Ø¯ Ø§Ù„Ø¬Ø§Ù…Ø¹ Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©',lineageCode:'A',birthYear:1850,parentId:'',spouseId:'',note:'Ø¹ÙŠÙ†Ø© Ø£Ø¯Ø§Ø¡ Ù…Ø­Ù„ÙŠØ© ÙÙ‚Ø·',living:false};let generated=[root];for(let branch=1;branch<=20;branch++){const parent={id:makeId(),name:`Ø§Ù„ÙØ±Ø¹ ${branch} Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©`,lineageCode:`A-${branch}`,birthYear:1880+branch,parentId:root.id,spouseId:'',note:'',living:false};generated.push(parent);for(let i=1;i<=59;i++) generated.push({id:makeId(),name:`ÙØ±Ø¯ ØªØ¬Ø±ÙŠØ¨ÙŠ ${branch}-${i} Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©`,lineageCode:`A-${branch}-${i}`,birthYear:1910+i,parentId:parent.id,spouseId:'',note:'',living:i>45});}state.people=generated;state.expanded=new Set([root.id]);audit('Ø§Ø®ØªØ¨Ø§Ø± Ø£Ø¯Ø§Ø¡','Ø¥Ù†Ø´Ø§Ø¡ Ø¹ÙŠÙ†Ø© Ù…Ø­Ù„ÙŠØ© Ù…Ù† 1,201 Ø´Ø®Øµ');save();renderAll();centerTree(root.id);toast('ØªÙ… ØªØ­Ù…ÙŠÙ„ Ø¹ÙŠÙ†Ø© Ø§Ù„Ø£Ø¯Ø§Ø¡. Ø§Ù„ÙØ±ÙˆØ¹ Ù…Ø§ Ø²Ø§Ù„Øª Ù…Ø·ÙˆÙŠØ© Ù„Ø¶Ù…Ø§Ù† Ø§Ù„Ø³Ù„Ø§Ø³Ø©.');}
// Pointer and pinch navigation. No scroll hijacking outside the canvas.
let pointers=new Map(),dragStart=null,pinchStart=null;const canvas=$('#treeCanvas');canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){dragStart={x:e.clientX,y:e.clientY,tx:state.transform.x,ty:state.transform.y};canvas.classList.add('dragging')}if(pointers.size===2){const a=[...pointers.values()];pinchStart={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale:state.transform.scale};}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&dragStart){state.transform.x=dragStart.tx+e.clientX-dragStart.x;state.transform.y=dragStart.ty+e.clientY-dragStart.y;applyTransform()}else if(pointers.size===2&&pinchStart){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);state.transform.scale=Math.max(.38,Math.min(1.8,pinchStart.scale*d/pinchStart.d));applyTransform();}});function release(e){pointers.delete(e.pointerId);dragStart=null;pinchStart=null;canvas.classList.remove('dragging')}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('wheel',e=>{e.preventDefault();state.transform.scale=Math.max(.38,Math.min(1.8,state.transform.scale*(e.deltaY>0?.9:1.1)));applyTransform()},{passive:false});
$('#treeWorld').addEventListener('click',e=>{const toggle=e.target.closest('[data-toggle]');if(toggle){const id=toggle.dataset.toggle;state.expanded.has(id)?state.expanded.delete(id):state.expanded.add(id);renderTree();return}const node=e.target.closest('[data-id]');if(node)focusPerson(node.dataset.id);});
$('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));$('#searchResults').addEventListener('click',e=>{const hit=e.target.closest('[data-focus]');if(hit){focusPerson(hit.dataset.focus);$('#searchInput').value='';renderSearch();}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')$$('.modal.open').forEach(x=>closeModal(x.id));});
$('#zoomIn').onclick=()=>{state.transform.scale=Math.min(1.8,state.transform.scale+0.15);applyTransform()};$('#zoomOut').onclick=()=>{state.transform.scale=Math.max(.38,state.transform.scale-.15);applyTransform()};$('#recenter').onclick=()=>centerTree(state.selected||roots()[0]?.id);$('#collapseAll').onclick=()=>{state.expanded=new Set();renderTree();centerTree(roots()[0]?.id)};$$('[data-layout]').forEach(b=>b.onclick=()=>{$$('[data-layout]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.layout=b.dataset.layout;renderTree();centerTree(state.selected||roots()[0]?.id);});
$('#adminBtn').onclick=()=>{renderAdmin();openModal('adminModal')};$('#helpBtn').onclick=()=>{openModal('adminModal');setTimeout(()=>document.querySelector('[data-tab=about]').click(),0)};$('#homeBtn').onclick=()=>{state.selected=null;renderTree();centerTree(roots()[0]?.id)};$('#requestBtn').onclick=()=>openModal('requestModal');$$('[data-close]').forEach(b=>b.onclick=()=>{closeModal(b.dataset.close);if(b.dataset.close==='personPanel'){$('#personPanel').classList.remove('open')}});$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
$('.admin-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;$$('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-tab').forEach(x=>x.classList.toggle('active',x.id==='tab-'+b.dataset.tab));});$('#addPersonBtn').onclick=()=>openEditor();$('#seedLargeBtn').onclick=seedLarge;$('#undoBtn').onclick=undo;$('#adminPeople').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(b.dataset.edit)});$('#personContent').addEventListener('click',e=>{const f=e.target.closest('[data-panel-focus]');if(f?.dataset.panelFocus)focusPerson(f.dataset.panelFocus);const req=e.target.closest('[data-request-person]');if(req){closeModal('personPanel');$('#personPanel').classList.remove('open');openModal('requestModal');$('#requestForm').elements.personRef.value=req.dataset.requestPerson;}});
$('#personForm').addEventListener('input',previewRelationship);$('#personForm').addEventListener('submit',e=>{e.preventDefault();if(!previewRelationship())return toast('ØµØ­Ø­ Ø§Ù„Ø±Ø¨Ø· Ù‚Ø¨Ù„ Ø§Ù„Ø­ÙØ¸.');const f=Object.fromEntries(new FormData(e.target));const existing=person(f.id), action=existing?'ØªØ¹Ø¯ÙŠÙ„ Ø¨ÙŠØ§Ù†Ø§Øª':'Ø¥Ø¶Ø§ÙØ© Ø´Ø®Øµ';snapshot(action);if(existing)Object.assign(existing,{...f,birthYear:f.birthYear?+f.birthYear:'',living:f.living==='true'});else state.people.push({id:makeId(),...f,birthYear:f.birthYear?+f.birthYear:'',living:f.living==='true'}); if(f.spouseId){const mate=person(f.spouseId);if(mate)mate.spouseId=existing?.id||state.people.at(-1).id;}audit(action,f.name);save();renderAll();closeModal('editorModal');toast('ØªÙ… Ø§Ù„Ø­ÙØ¸ Ù…Ø­Ù„ÙŠÙ‹Ø§ Ù…Ø¹ ØªØ³Ø¬ÙŠÙ„Ù‡ ÙÙŠ Ø§Ù„Ø³Ø¬Ù„.');});$('#deletePersonBtn').onclick=()=>{const id=$('#personForm').elements.id.value,p=person(id);if(!p||children(id).length)return toast('Ù„Ø§ ÙŠÙ…ÙƒÙ† Ø­Ø°Ù Ø´Ø®Øµ Ù„Ù‡ Ø£Ø¨Ù†Ø§Ø¡Ø› Ø§Ù†Ù‚Ù„ Ø§Ù„Ø±ÙˆØ§Ø¨Ø· Ø£ÙˆÙ„Ù‹Ø§.');if(!confirm(`Ø­Ø°Ù ${p.name}ØŸ ÙŠÙ…ÙƒÙ† Ø§Ù„ØªØ±Ø§Ø¬Ø¹ Ø¨Ø¹Ø¯ Ø§Ù„Ø­Ø°Ù.`))return;snapshot('Ø­Ø°Ù Ø´Ø®Øµ');state.people=state.people.filter(x=>x.id!==id);state.people.forEach(x=>{if(x.spouseId===id)x.spouseId=''});audit('Ø­Ø°Ù Ø´Ø®Øµ',p.name);save();renderAll();closeModal('editorModal');toast('ØªÙ… Ø§Ù„Ø­Ø°Ù.');};
$('#requestForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const ref=`AN-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,body=`Ø·Ù„Ø¨ ØªØ¹Ø¯ÙŠÙ„ Ø´Ø¬Ø±Ø© Ø¹Ø§Ø¦Ù„Ø© Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ©\n\nØ±Ù‚Ù… Ø§Ù„Ù…Ø±Ø¬Ø¹: ${ref}\nØ§Ù„Ø§Ø³Ù…: ${f.requesterName}\nØ§Ù„Ù‡Ø§ØªÙ: ${f.phone}\nØ§Ù„Ø¨Ø±ÙŠØ¯: ${f.email||'ØºÙŠØ± Ù…Ø¶Ø§Ù'}\nÙ…Ø±Ø¬Ø¹ Ø§Ù„Ø´Ø®Øµ: ${f.personRef||'ØºÙŠØ± Ù…Ø­Ø¯Ø¯'}\n\nØ§Ù„ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ù…Ù‚ØªØ±Ø­:\n${f.message}\n\nÙ…Ù„Ø§Ø­Ø¸Ø©: Ø¥Ø°Ø§ Ø·Ù„Ø¨ Ù…Ù†Ùƒ Ø§Ù„Ù…Ø´Ø±Ù Ø¥Ø«Ø¨Ø§ØªÙ‹Ø§ØŒ Ø£Ø±ÙÙ‚Ù‡ ÙÙŠ Ø±Ø³Ø§Ù„Ø© Ø§Ù„Ø¨Ø±ÙŠØ¯ ÙÙ‚Ø·. Ù„Ø§ ØªØ±ÙØ¹Ù‡ Ø¥Ù„Ù‰ Ø§Ù„Ù…ÙˆÙ‚Ø¹.`;$('#requestResult').textContent=`ØªÙ… ØªØ­Ø¶ÙŠØ± Ø§Ù„Ø±Ø³Ø§Ù„Ø© Ø¨Ø±Ù‚Ù… ${ref}. Ø³ÙŠÙØªØ­ ØªØ·Ø¨ÙŠÙ‚ Ø§Ù„Ø¨Ø±ÙŠØ¯ Ù„Ø¯ÙŠÙƒØ› Ù„Ù… ÙŠØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø£ÙŠ Ø±Ø³Ø§Ù„Ø© Ù…Ù† Ø§Ù„Ù…ÙˆÙ‚Ø¹.`;window.location.href=`mailto:?subject=${encodeURIComponent('Ø·Ù„Ø¨ ØªØ¹Ø¯ÙŠÙ„ Ø´Ø¬Ø±Ø© Ø§Ù„Ø¹Ù†Ø§Ø³ÙˆØ© '+ref)}&body=${encodeURIComponent(body)}`;});
state.expanded.add(roots()[0]?.id);renderAll();requestAnimationFrame(()=>centerTree(roots()[0]?.id));

